version: '3'
services:
  server1:
    build: ./server1
    container_name: p5serv
  server2:
    image: nginx
    container_name: serv2cont
    ports:
      - "80:8080"
    volumes:
      - ./server2/nginx/nginx.conf:/etc/nginx/nginx.conf